const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

exports.generateTrainingReport = async (athleteData, workouts, performance) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const fileName = `athleteiq-training-report-${athleteData._id}-${Date.now()}.pdf`;
      const filePath = path.join(__dirname, '../reports', fileName);

      if (!fs.existsSync(path.join(__dirname, '../reports'))) {
        fs.mkdirSync(path.join(__dirname, '../reports'), { recursive: true });
      }

      const stream = fs.createWriteStream(filePath);
      doc.pipe(stream);

      doc.fontSize(24).fillColor('#2563eb').text('AthleteIQ', { align: 'center' });
      doc.fontSize(12).fillColor('#666').text('Smart Coaching Platform', { align: 'center' });
      doc.moveDown();
      doc.fontSize(18).fillColor('#000').text('Training Performance Report', { align: 'center' });
      doc.moveDown(2);

      doc.fontSize(14).text(`Athlete: ${athleteData.name}`);
      doc.fontSize(12).text(`Email: ${athleteData.email}`);
      doc.text(`Sports Category: ${athleteData.sportsCategory || 'N/A'}`);
      doc.text(`Report Generated: ${new Date().toLocaleDateString()}`);
      doc.moveDown();

      doc.fontSize(16).fillColor('#2563eb').text('Workout Summary', { underline: true });
      doc.fillColor('#000');
      doc.moveDown();
      doc.fontSize(12).text(`Total Workouts Completed: ${workouts.length}`);
      
      const totalDuration = workouts.reduce((sum, w) => sum + (w.totalDuration || 0), 0);
      const totalCalories = workouts.reduce((sum, w) => sum + (w.caloriesBurned || 0), 0);
      
      doc.text(`Total Training Duration: ${Math.round(totalDuration / 60)} hours`);
      doc.text(`Total Calories Burned: ${totalCalories} kcal`);
      doc.moveDown();

      if (workouts.length > 0) {
        doc.fontSize(14).fillColor('#2563eb').text('Recent Workouts:', { underline: true });
        doc.fillColor('#000');
        doc.moveDown();
        
        workouts.slice(0, 10).forEach((workout, index) => {
          doc.fontSize(11);
          doc.text(`${index + 1}. ${new Date(workout.date).toLocaleDateString()}`);
          doc.fontSize(10);
          doc.text(`   Duration: ${workout.totalDuration} min | Difficulty: ${workout.difficultyRating}/10`);
          doc.text(`   Fatigue Level: ${workout.fatigueLevel}/10 | Mood: ${workout.mood || 'N/A'}`);
          if (workout.notes) {
            doc.text(`   Notes: ${workout.notes.substring(0, 100)}...`);
          }
          doc.moveDown(0.5);
        });
      }

      doc.addPage();
      doc.fontSize(16).fillColor('#2563eb').text('Performance Metrics', { underline: true });
      doc.fillColor('#000');
      doc.moveDown();

      if (performance.length > 0) {
        const latest = performance[0];
        doc.fontSize(12);
        
        if (latest.metrics) {
          doc.text('Latest Measurements:');
          doc.fontSize(11);
          if (latest.metrics.weight) doc.text(`Weight: ${latest.metrics.weight} kg`);
          if (latest.metrics.bodyFat) doc.text(`Body Fat: ${latest.metrics.bodyFat}%`);
          if (latest.metrics.muscleMass) doc.text(`Muscle Mass: ${latest.metrics.muscleMass} kg`);
          if (latest.metrics.vo2Max) doc.text(`VO2 Max: ${latest.metrics.vo2Max}`);
          if (latest.metrics.restingHeartRate) doc.text(`Resting Heart Rate: ${latest.metrics.restingHeartRate} bpm`);
          doc.moveDown();

          if (latest.metrics.strength) {
            doc.fontSize(12).text('Strength Metrics:');
            doc.fontSize(11);
            if (latest.metrics.strength.benchPress) doc.text(`Bench Press: ${latest.metrics.strength.benchPress} kg`);
            if (latest.metrics.strength.squat) doc.text(`Squat: ${latest.metrics.strength.squat} kg`);
            if (latest.metrics.strength.deadlift) doc.text(`Deadlift: ${latest.metrics.strength.deadlift} kg`);
            doc.moveDown();
          }

          if (latest.metrics.endurance) {
            doc.fontSize(12).text('Endurance Metrics:');
            doc.fontSize(11);
            if (latest.metrics.endurance.runTime5k) doc.text(`5K Run Time: ${latest.metrics.endurance.runTime5k} min`);
            if (latest.metrics.endurance.runTime10k) doc.text(`10K Run Time: ${latest.metrics.endurance.runTime10k} min`);
            if (latest.metrics.endurance.plankDuration) doc.text(`Plank Duration: ${latest.metrics.endurance.plankDuration} sec`);
            doc.moveDown();
          }
        }
      } else {
        doc.fontSize(11).text('No performance data recorded yet.');
      }

      doc.moveDown(2);
      doc.fontSize(10).fillColor('#666').text('This report was automatically generated by AthleteIQ - Smart Coaching Platform', { align: 'center' });

      doc.end();

      stream.on('finish', () => {
        resolve({ success: true, filePath, fileName });
      });

      stream.on('error', (error) => {
        reject(error);
      });

    } catch (error) {
      reject(error);
    }
  });
};

exports.generatePlanReport = async (plan, athletesData) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const fileName = `athleteiq-plan-report-${plan._id}-${Date.now()}.pdf`;
      const filePath = path.join(__dirname, '../reports', fileName);

      if (!fs.existsSync(path.join(__dirname, '../reports'))) {
        fs.mkdirSync(path.join(__dirname, '../reports'), { recursive: true });
      }

      const stream = fs.createWriteStream(filePath);
      doc.pipe(stream);

      doc.fontSize(24).fillColor('#2563eb').text('AthleteIQ', { align: 'center' });
      doc.fontSize(12).fillColor('#666').text('Smart Coaching Platform', { align: 'center' });
      doc.moveDown();
      doc.fontSize(18).fillColor('#000').text('Training Plan Report', { align: 'center' });
      doc.moveDown(2);

      doc.fontSize(14).text(`Plan: ${plan.title}`);
      doc.fontSize(12).text(`Category: ${plan.category}`);
      doc.text(`Duration: ${plan.duration.weeks} weeks`);
      doc.text(`Sessions per Week: ${plan.duration.sessionsPerWeek}`);
      doc.text(`Start Date: ${new Date(plan.startDate).toLocaleDateString()}`);
      doc.text(`End Date: ${new Date(plan.endDate).toLocaleDateString()}`);
      doc.text(`Status: ${plan.status}`);
      doc.moveDown();

      doc.fontSize(14).fillColor('#2563eb').text('Description:', { underline: true });
      doc.fillColor('#000');
      doc.fontSize(11).text(plan.description);
      doc.moveDown();

      if (athletesData && athletesData.length > 0) {
        doc.fontSize(14).fillColor('#2563eb').text(`Assigned Athletes (${athletesData.length}):`, { underline: true });
        doc.fillColor('#000');
        doc.moveDown();
        athletesData.forEach((athlete, index) => {
          doc.fontSize(11).text(`${index + 1}. ${athlete.name} (${athlete.email})`);
        });
        doc.moveDown();
      }

      if (plan.workouts && plan.workouts.length > 0) {
        doc.addPage();
        doc.fontSize(16).fillColor('#2563eb').text('Workout Schedule', { underline: true });
        doc.fillColor('#000');
        doc.moveDown();

        plan.workouts.forEach((workout, index) => {
          doc.fontSize(12).text(`Day ${workout.day}: ${workout.title}`);
          
          if (workout.restDay) {
            doc.fontSize(11).fillColor('#2563eb').text('   REST DAY');
            doc.fillColor('#000');
          } else if (workout.exercises && workout.exercises.length > 0) {
            workout.exercises.forEach((exercise, exIndex) => {
              doc.fontSize(10);
              doc.text(`   ${exIndex + 1}. ${exercise.name}`);
              if (exercise.sets) doc.text(`      Sets: ${exercise.sets} | Reps: ${exercise.reps || 'N/A'}`);
              if (exercise.duration) doc.text(`      Duration: ${exercise.duration}`);
              if (exercise.intensity) doc.text(`      Intensity: ${exercise.intensity}`);
            });
          }
          doc.moveDown(0.5);
        });
      }

      doc.moveDown(2);
      doc.fontSize(10).fillColor('#666').text('Generated by AthleteIQ - Smart Coaching Platform', { align: 'center' });

      doc.end();

      stream.on('finish', () => {
        resolve({ success: true, filePath, fileName });
      });

      stream.on('error', (error) => {
        reject(error);
      });

    } catch (error) {
      reject(error);
    }
  });
};
